name: Audit Renovate Config
on: pull_request
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coveo/public-actions/audit-renovate-config@CIA-583/audit-renovate-config
